spring.application.name=api-gateway

server.port=8087

# Student Management Microservice
spring.cloud.gateway.routes[0].id=student-service

spring.cloud.gateway.routes[0].uri=http://localhost:8084

spring.cloud.gateway.routes[0].predicates[0]=Path=/students/**